INSERT INTO System_User (
    System_User_Code,
    System_User_Name,
    System_User_BirthDay,
    System_User_Gender,
    System_User_PhoneNumber,
    System_User_Address,
    System_User_Email,
    System_User_Roles,
    System_User_Password,
    System_User_Permission,
    Status,
    System_User_ChangePassword,
    CreateBy,
    UpdateBy
) VALUES (
    'USER001',
    'Trương Chí Kiên',
    '2002-11-15',
    'Nam',
    0968727900,
    '268/23 Lê Văn Việt, Tăng Nhơn Phú B, Quận 9, TP.HCM',
    'truongchikien2021@example.com',
    1,
    '123',
    'ADMIN',
    'ACTIVE',
    false,
    'admin',
    'admin'
);
